language: java
install: true

jdk:
  - oraclejdk8

script:
  - cd /thirdparty/googletest-master/ && cmake . && make
  - chmod +x gradlew
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/